# work in progress
# should be later included into thomass/common and working for all major distributions

- name: install python openssl
  become: true
  apt:
    name: python-openssl
    state: present
    update-cache: yes
 
- name: install acl to allow unprivileged become_user
  become: true
  apt:
    name: acl
    state: present
