---

- name: ensure git user has a private key for executing push hooks got gitlab.com and github.com
  become: yes
  openssl_privatekey:
    path: /var/opt/gitlab/.ssh/id_rsa
    size: 4096
    type: RSA
    owner: git
    group: git

- name: ensure git user has public key from private key
  become: yes
  openssl_publickey:
    path: /var/opt/gitlab/.ssh/id_rsa.pub
    privatekey_path: /var/opt/gitlab/.ssh/id_rsa

- name: trust current public keys of gitlab.com and github.com
  become: yes
  become_user: git
  known_hosts:
    path: /var/opt/gitlab/.ssh/known_hosts
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -trsa {{ item }}') }}"
  with_items:
    - gitlab.com
    - github.com

- name: create ssh key on gitlab.com
  become: yes
  uri:
    url: "https://gitlab.com/api/v4/user/keys"
    method: POST
    body: "{ \"title\": \"{{ ansible_hostname }}-mirror\", \"key\": \"{{ lookup('file', '/var/opt/gitlab/.ssh/id_rsa.pub') }}\" }"
    body_format: json
    headers:
      Private-Token: "{{ GITLAB_TOKEN }}"
    return_content: yes
    timeout: 120
  register: result
  changed_when: "result.status == 201"
  failed_when: "result.status != 201 and 'has already been taken' not in result.content"

- name: create ssh key on github.com
  become: yes
  uri:
    url: "https://api.github.com/user/keys"
    method: POST
    body: "{ \"title\": \"{{ ansible_hostname }}-mirror\", \"key\": \"{{ lookup('file', '/var/opt/gitlab/.ssh/id_rsa.pub') }}\" }"
    body_format: json
    headers:
      Authorization: "token {{ GITHUB_TOKEN }}"
    return_content: yes
    timeout: 120
  when: item.visibility == 'public'
  register: result
  changed_when: "result.status == 201"
  failed_when: "result.status != 201 and 'key is already in use' not in result.content"
