---
- name: ensure git user has a private key for executing push hooks got gitlab.com and github.com
  become: yes
  openssl_privatekey:
    path: /var/opt/gitlab/.ssh/id_rsa
    size: 4096
    type: RSA
    owner: git
    group: git

- name: query users repositories where he is at least developer
  uri:
    url: "{{ SOURCE_GITLAB_URL }}/api/v4/projects?per_page={{ project_query_size }}&min_access_level=30"
    method: GET                
    headers:
      Private-Token: "{{ SOURCE_GITLAB_TOKEN }}"
    return_content: yes
    timeout: 120               
  register: result

- name: extract repositories list
  set_fact:
    projectlist: "{{ result.content | from_json }}"

- name: query user information
  uri:
    url: "{{ SOURCE_GITLAB_URL }}/api/v4/user"
    method: GET
    headers:
      Private-Token: "{{ SOURCE_GITLAB_TOKEN }}"
    return_content: yes
    timeout: 120
  register: result

- name: extract username to differ repositories which are from groups
  set_fact:
    username: "{{ (result.content | from_json).username }}"

- name: query gitlab.com user information
  uri:
    url: "https://gitlab.com/api/v4/user"
    method: GET
    headers:
      Private-Token: "{{ GITLAB_TOKEN }}"
    return_content: yes
    timeout: 120
  register: result

- name: extract username to differ repositories which are from groups
  set_fact:
    gitlabcom_username: "{{ (result.content | from_json).username }}"

- name: query github.com user information
  uri:
    url: "https://api.github.com/user"
    method: GET
    headers:
      Authorization: "token {{ GITHUB_TOKEN }}"
    return_content: yes
    timeout: 120
  register: result

- name: extract username to differ repositories which are from groups
  set_fact:
    githubcom_username: "{{ (result.content | from_json).login }}"

- name: setup gitlab repository clones
  include_tasks: setup-clone.yml
  with_items: "{{ projectlist }}"
  when: item.path_with_namespace not in ignored_repositories
