- debug:
    msg: "Processing repo {{ item.path_with_namespace }}"

- name: create repo on gitlab.com
  become: no
  uri:
    url: "https://gitlab.com/api/v4/projects"
    method: POST
    body: "{ \"name\": \"{{ (item.namespace.name + '-') when item.namespace.name != username }}{{ item.path }}\", \"visibility\": \"{{ item.visibility }}\", \"description\": \"Clone of {{ item.http_url_to_repo }}\", \"issues_enabled\": false, \"merge_requests_enabled\": false, \"jobs_enabled\": false, \"wiki_enabled\": false, \"snippets_enabled\": false, \"container_registry_enabled\": false, \"shared_runners_enabled\": false }"
    body_format: json
    headers:
      Private-Token: "{{ GITLAB_TOKEN }}"
    return_content: yes
    timeout: 120
  register: result
  changed_when: "result.status == 201"
  failed_when: "result.status != 201 and 'has already been taken' not in result.content"

- name: create repo on github.com
  become: no
  uri:
    url: "https://api.github.com/user/repos"
    method: POST
    body: "{ \"name\": \"{{ (item.namespace.name + '-') when item.namespace.name != username }}{{ item.path }}\", \"description\": \"Clone of {{ item.http_url_to_repo }}\", \"has_issues\": false, \"has_projects\": false, \"has_wiki\": false }"
    body_format: json
    headers:
      Authorization: "token GITHUB_TOKEN"
    return_content: yes
    timeout: 120
  when: item.visibility == 'public'
  register: result
  changed_when: "result.status == 201"
  failed_when: "result.status != 201 and 'name already exists on this account' not in result.content"

- name: get owner and group of repository dir
  stat:
    path: "{{ source_repository_path }}/{{ item.path_with_namespace }}.git"
  register: sourceDir

- name: create custom_hooks directory
  file:
    path: "{{ source_repository_path }}/{{ item.path_with_namespace }}.git/custom_hooks"
    owner: "{{ sourceDir.stat.uid }}"
    group: "{{ sourceDir.stat.gid }}"
    state: directory

- name: setup post-receive hook to push clone
  template:
    src: post-receive.j2
    dest: "{{ source_repository_path }}/{{ item.path_with_namespace }}.git/custom_hooks/post-receive"
    owner: "{{ sourceDir.stat.uid }}"
    group: "{{ sourceDir.stat.gid }}"
    mode: 0750
