- name: example playbook
  hosts: aci-target
  roles:
    - role: gitlab-mirroring
      source_repository_path: /var/opt/gitlab/git-data/repositories
      ignored_repositories:
        - root/config
